scan_timeout = 30
command_timeout = 300
add_newline = true

[cmd_duration]
style = "bold blue"

[character]
success_symbol = "[❯](bold blue) "

[directory]
truncation_length = 2

[time]
disabled = true
style = "white"

[username]
show_always = false
style_user = "bold blue"

[hostname]
ssh_only = true
style = "bold white"

[git_branch]
symbol = " "

[git_commit]
commit_hash_length = 5
only_detached = false
style = "bold purple"
tag_disabled = false

[git_metrics]
disabled = false

[python]
symbol = " "

[cmake]
symbol = " "

[c]
symbol = " "
format = "via [$symbol]($style)"
style = "bold blue"

[nodejs]
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts", "qml", "qrc"]
format = "via [$symbol]($style)"
